version: '3'

services:

  sqlite-db:
    image: alpine:latest
    command: sh -c "apk add --no-cache sqlite && sqlite3 /usr/src/app/database/arosaje.db .schema > /usr/src/app/database/arosaje_schema.sql"
    volumes:
      - ./database:/usr/src/app/database

  api-back:
    image: node:20
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - ./database:/usr/src/app/database
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"