version: '3'

services:
  api-back:
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    volumes:
      - ./database:/usr/src/app/database
    build:
      context: ./backend
      dockerfile: Dockerfile
  angular-app:
    ports:
      - "4200:4200"
    build:
      context: ./frontend
      dockerfile: Dockerfile