version: '3'

services:
  sqlite-db:
    build:
      context: .
      dockerfile: data/Dockerfile
    ports:
      - "5432:5432"
  api-back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"