name: Node.js CI

on:
  push:
    branches: [ separation-des-apps ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create SQLite database
        run: |
          sqlite3 arosaje.db < arosaje_schema.sql
        working-directory: database
      - name: Install dependencies and run tests
        run: |
          npm install
          npm ci
          npm run build --if-present
          npm test

        working-directory: backend